### ISSUE TITLE
Hola Reinier 

### ISSUE THREAD

**Issue by garisbaldy** [ReinierTutoriales/Hackintosh-Gigabyte-X570-AORUS-ELITE#1]
Tengo una pregunta está EFI funciona correctamente sin problemas en mi ordenador tengo la placa aorus pro WiFi B450 , Ryzen 5 3600 XT , 16 ram t force , y GPU Rx 570 aorus,

**Comment by ReinierTutoriales** [comment]
Ya actualicé la EFI.
